name: Release Workflow

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Run zipper script
        run: |
          chmod +x ./zipper.sh
          ./zipper.sh ${{ github.ref_name }}

      - name: Upload release assets
        uses: softprops/action-gh-release@v1
        with:
          tag: ${{ github.ref_name }}
          files: cities-out/**
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit & Push changes
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          message: "Update release files for ${{ github.ref_name }}"
